services:
  redis:
    image: redis:8.2-alpine
    container_name: redis_aplyer
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis_data:
